name: NodeJS with Webpack

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    #strategy:
    #  matrix:
    #    node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build
      run: |
        cd web
        npm install
        npx webpack



    # commit new package to kivyswiftlink/master
    - name: commit to master
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
      with:
        source-directory: './'
        destination-github-username: 'psychowasp'
        destination-repository-name: 'SwiftyMonaco'
        user-email: pythonswiftlink@gmail.com
        target-branch: main



        
